---
wg_interface: wg0
wg_port: 51820
wg_tunnel_ip: "10.0.0.1/24"
wg_peer_public_key: ""
wg_peer_endpoint: ""
wg_peer_allowed_ips: "10.0.0.2/32"
wg_forward_target: "10.0.0.2"
wg_config_dir: /etc/wireguard
edge_packages:
  - wireguard-tools
  - iptables-services
  - curl
  - htop
