---
# ==============================================================================
# K3s prerequisites role defaults
# ==============================================================================

k3s_role_packages: []
k3s_firewall_ports: []
enable_iscsid: false
