apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: hafletjm01@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            email: hafletjm01@gmail.com
            apiTokenSecretRef:
              # TODO: Create a SealedSecret or regular Secret containing your
              # Cloudflare API token with Zone:DNS:Edit permissions.
              # kubectl create secret generic cloudflare-api-token-secret \
              #   --namespace cert-manager \
              #   --from-literal=api-token=<your-cloudflare-api-token>
              name: cloudflare-api-token-secret
              key: api-token
