---
# ==============================================================================
# K3s agent role defaults
# ==============================================================================

k3s_version: "v1.31.4+k3s1"
k3s_server_url: "https://192.168.1.100:6443"
k3s_agent_args: ""
